version: "2"

networks:
  default:
    external:
      name: chatbot

services:
  chatbot-service:
    image: jurebevc/chatbot-chatbots
    container_name: chatbot-chatbots
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8084:8084